config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => {:sessions => "sessions"}

  devise_scope :user do 
    delete "/users/sign_out" => "devise/sessions#destroy" 
  end

  resources :users, only: [:show] do
    resources :clients, only: [:show, :new, :edit] do
    end
  end

  get '/clients/:id/history', to: 'clients#history' # custom route
  
  resources :clients, only: [:show, :index, :create, :update, :delete] do
      resources :history, :labs, :fullassessments, :progressnotes, :monitoringnotes, :nextevaluationnotes, :goals
  end
  
  root 'pages#home'

  get '#processingViewModal', to: 'pages#home' # hack in the meantime

  get '/dashboard', to: 'pages#dashboard'



 
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :timeoutable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :clients
  has_many :progressnotes, through: :clients
  has_many :nextevaluationnotes, through: :clients
  has_many :monitoringnotes, through: :clients
  has_many :fullassessments, through: :clients
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, 
         :validatable, :authentication_keys => [:username]

    def email_required?
       false
    end
     
    def email_changed?
       false
    end

  def all_clients_records
    self.clients.map { |client| client.medical_record }.first
  end

  def history
    @all_docs = {
      fullassessments: self.fullassessments,
      progressnotes: self.progressnotes,
      monitoringnotes: self.monitoringnotes,
      labs: self.labs,
      goals: self.goals,
      nextevaluationnotes: self.nextevaluationnotes
    }
  end

end

  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field like 'username'

app/models/users.rb
class Users < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: [:twitter]
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /current_users
  # GET /current_users.json
  def index
    @users = User.all
  end

  # GET /current_users/1
  def show
    @user = User.find(params[:id])
  end
  

  # GET /current_users/new
  def new
    @user = CurrentUser.new
    redirect_to '/sessions/new'
  end

  # GET /current_users/1/edit
  def edit
  end

  # POST /current_users
  # POST /current_users.json
  def create
    @user = CurrentUser.new(current_user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Current user was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /current_users/1
  # PATCH/PUT /current_users/1.json
  def update
    respond_to do |format|
      if @user.update(current_user_params)
        format.html { redirect_to @user, notice: 'Current user was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /current_users/1
  # DELETE /current_users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to current_users_url, notice: 'Current user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      return if params[:id] == "sign_out"
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def current_user_params
      params.fetch(:user, {})
    end
end

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
c

app/views/users/edit.html.erb
<!-- MOBILE STOPPER -->
    <div id="mobileStopper" class="preloader table-wrapper" style="background: #b2d5d6;display:none">
      <div class="table-row">
        <div id='contente' style="height: 100%;width: 90%;position: absolute;top: 30%;left:5%">
          <div>

<p>
              <h2 style="text-align: center">Mobile Devices Not Yet Supported.</h2>
                  <h4 style="text-align: center">Use a desktop to experience the new Medical Nutrition Therapy process.</h4>
          


           <div style="position: center; text-align: center;margin:80% 20% 0% 20%">
             
            <h1 style="font-size: 16px">© Carlos Almonte 2017</h1>
</div>
           </p>

          </div>
        </div>
      </div>
    </div>


      <%= render partial: 'pages/header' %>
      <div id="fade" class="center" style="display: none;height:100%">
        <div id="jumbotronnoblur" class="" style="width:100%;height:100%;position: absolute;sund-color: #FFFFFFF">
        </div>

        <div class="table-cell text-center animated fadeIn" style="position: absolute;top: 20%; height:100%; width: 100%">

          <!-- SIGN IN BLOCK -->
        <div id="new_user1" class="login i-block animated fadeInUp" style="position: absolute;width: 300px; height: 360px;left: 40%">
          <div class="content-box" style="height: 360px">
            <div class="" style="margin-left: 10%;width: 100%; height: 100%;background-image: url('<%= asset_path('Logo SOS w name.png') %>');background-repeat:no-repeat; background-size:contain; height:150px; left: 50%" >
            </div>
            <div class="big-box text-left login-form" style="padding: 0 50px 120px; margin: -13px 0 0 0">
              <!-- SIGN IN FORM -->
                        <%= form_for(resource, as: resource_name, url: session_path(resource_name), :html => {style: "position: absolute", remote: true}) do |f| %>
          <%= devise_error_messages! %>
            <%= f.text_field :username, class: "form-control material", placeholder: "Username", id: "login", type: "text", value: "iamaguest", autofocus: true, style: "margin:10px 20px 10px 0"%>
            <%= f.password_field :password, class: "form-control material", placeholder: "Password", id: "password", type: "password", autocomplete: "off", value: "iamaguest", style: "margin:10px 20px 10px 0"%>
          <div class="text-uppercase" style="margin:20px 0 10px 0">
            <%= f.submit "Log In", name:"submit",class: "btn btn-block btn-info text-uppercase", style:"border:none;background: #374b89;text-transform:uppercase;color: #FFFFFF"%>
          </div>
          <a id="registerBtn" class="btn btn-block btn-warning text-uppercase" style"">Create an account</a>
          <a href="#" class="green i-block" style="margin: 10px 0 0 0">Forgot password?</a>
          <% end %>
            </div>
          </div>
        </div>
        <!-- SIGN IN BLOCK ENDS -->

<!-- SIGN UP BLOCK BEGINS -->
                <div id="sign_up_user1" class="login i-block animated zoomOut" style="position: absolute; display: none;width: 300px; height: 360px;left: 40%">
          <div class="content-box" style="height: 360px">
            <div class="" style="margin-left: 10%;width: 100%; height: 100%;background-image: url('<%= asset_path('Logo SOS w name.png') %>');background-repeat:no-repeat; background-size:contain; height:150px; left: 50%" >
            </div>
            <div class="big-box text-left login-form" style="padding: 0 50px 120px; margin: -13px 0 0 0">

          <!-- SIGN UP FORM -->
              <%= form_for(resource, as: resource_name, url: registration_path(resource_name), :html => {class: "", :id => "sign_up_user", :style => "display: block;position: absolute;"}) do |f| %>
          <%= devise_error_messages! %>
            <%= f.text_field :username, class: "input-container form-control material", placeholder: "Username", id: "login", type: "text", autofocus: true%>
            <%= f.password_field :password, class: "input-container form-control material", placeholder: "Password", id: "password", type: "password", autocomplete: "off"%>
            <%= f.password_field :password_confirmation, class: "input-container form-control material", placeholder: "Password Confirmation", id: "passwordconfirm", autocomplete: "off" %>
          <div class="btn btn-warning text-uppercase" style="margin: 20px 0 10px 0; width: 100%">
            <%= f.submit "Register", name:"submit", style:"border:none;background:transparent;text-transform:uppercase"%>
          </div>
          <a id="logInBtn" class="btn btn-block text-uppercase" style="background-color: #374b89 ;color: #FFFFFF">Log In</a>
        </li>
          <% end %>
            </div>
          </div>
        </div>
        <!-- SIGN UP BLOCK END -->
      </div>
        <!-- <div style="left: 35%;height: 40%;width: 30%;position: absolute; top: 150px;background-image: url('<%= image_path('Logo SOS w name.png')%>'); background-size: cover"> -->
        </div>
      <!-- <img class="animated fadeInUp" id="jumbotronlogo" src="<%= image_path('jumbotronlogo.png')%>" alt="" style="position: absolute;top: 6em;left: 1em;width: 60%;display: none"> -->
      <div id="slogan" style="display: none;">
      <!-- <img class="animated fadeInUp" id="sloganpng" src="<%= image_path('slogan.png')%>" alt="" style="position: absolute;display: block;width: 30%;top: 21em;right: 8em"> -->
      </div>
      </div>
      <div id="divider1" class="col-lg-6" style="display: none;position: relative;background: #374b89;color:#FFFFFF; width:;height: 60%;padding: 3em 2em 3em 2em">
        <h2>About</h2>
          <h1>Dietitians Reinvented.</h1>
          <h3>Dietitian.help is an EMR for Dietitians that has broken down the Medical Nutrition Therapy process (MNT) in a way that will ensure that your client will receive the most accurate assessment, allowing you as healthcare provider to determine the most appropiate intervention. All while complying with regulatory bodies, e.g. Medicaid, Medicare, etc...</h3>
          <br>
          <h1>From top to bottom, designed to fit your needs</h1>
          <h3>Save notes in the format you were taught. Automatically perform a sample assessment to guide you in the right direction.</h3>
        </div>
        <div id="divider2" class="col-lg-6" style="display: none;height:60%;background-image: url('<%=image_path('egg.jpg')%>');background-position: 75% 75%;background-size: 100%">
          <div style="float: right;position: relative; width:100%;height: 100%;padding: 3em 2em 3em 2em">
        </div>
        </div>
      <!-- Pen Title-->
      <script>
      $('.toggle').on('click', function() {
      $('.container').stop().addClass('active');
      });
      $('.close').on('click', function() {
      $('.container').stop().removeClass('active');
      });
      $('body').attr('style', "background-image: url('<%= image_path('foodJumbo copy.jpg')%>');margin:0px;overflow: visible;background-size: cover")
      // LOGO DOES NOT GO ON BODY WHILE FADEING IN/OUT
      $('#gn-menu').attr('style', "overflow: hidden")

      // $('body').attr('style', "background: #a7bec5")

      $(document).ready(function(){
        $('#slogan').delay(1300).fadeIn(580);
        $('#jumbotronlogo').delay(1000).fadeIn(100);
  if($(window).width() > 960) {
        $('#fade').delay(200).show('fast');

        $('#divider1').delay(1000).fadeIn(100);
        $('#divider2').delay(1000).fadeIn(100);
        $('#footer').delay(1000).fadeIn(100);
        <% if flash[:notice] %>
          error()
        <% else%>
          setTimeout(inviter, 2000);
        <% end %>
      }
        //$('#jumbotronblur').delay(1000).fadeOut(5000);
        //$('#divider2').foggy({
          //  blurRadius: 1,          // In pixels.
        //});







        $('.top-clock').remove();
    $('#sign_up_user').attr('style', 'display: none');

      




// FADE IN BODY
$('body').show('fast');

      })


function error() {

  top.iziToast.show({
    color: '#374b89',
    icon: 'icon-person',
    titleColor: 'white',
    title: '<%= flash[:notice] %>',
    position: 'topRight', // bottomRight, bottomLeft, topRight, topLeft, topCenter, bottomCenter
    progressBarColor: 'white',
  });

}

function inviter() {

  top.iziToast.show({
    color: '#374b89',
    icon: 'icon-person',
    titleColor: 'white',
    title: 'Log In to Demo the App!',
    position: 'topRight', // bottomRight, bottomLeft, topRight, topLeft, topCenter, bottomCenter
    progressBarColor: 'white',
  });

}





      $('#registerBtn').click(function(e){
    
    e.preventDefault();

  $('#new_user1').toggleClass('fadeInUp zoomOut');
    $('#sign_up_user1').toggleClass('fadeInUp zoomOut');
    $('#sign_up_user1').show();
    $('#sign_up_user').show();


})
$('#logInBtn').click(function(e){

  e.preventDefault();

  $('#new_user1').toggleClass('fadeInUp zoomOut');
      $('#sign_up_user1').toggleClass('fadeInUp zoomOut');

})

// SCROLLS TO ABOUT
$("#aboutFromNav").click(function() {
    $('html, body').animate({
        scrollTop: $("#divider1").offset().top - 25
    }, 400);
});


function fadeAway() {
  $('html').fadeOut();
}




      </script>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
  <p id="notice"> <%= notice %> 
  </p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>