config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => {:sessions => "sessions"}

  devise_scope :user do 
    delete "/users/sign_out" => "devise/sessions#destroy" 
  end

  resources :users, only: [:show] do
    resources :clients, only: [:show, :new, :edit] do
    end
  end

  get '/clients/:id/history', to: 'clients#history' # custom route
  
  resources :clients, only: [:show, :index, :create, :update, :delete] do
      resources :history, :labs, :fullassessments, :progressnotes, :monitoringnotes, :nextevaluationnotes, :goals
  end
  
  root 'pages#home'

  get '#processingViewModal', to: 'pages#home' # hack in the meantime

  get '/dashboard', to: 'pages#dashboard'



 
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/client.rb
class Client < ApplicationRecord
	belongs_to :user
	has_many :fullassessments
	has_many :progressnotes
	has_many :monitoringnotes
	has_many :labs
	has_many :goals
	has_many :nextevaluationnotes

	def medical_records
		@all_docs = {
			client: self,
			fullassessments: self.fullassessments,
			progressnotes: self.progressnotes,
			monitoringnotes: self.monitoringnotes,
			labs: self.labs,
			goals: self.goals,
			nextevaluationnotes: self.nextevaluationnotes
		}
	end

	def name
		self.firstname + " " + self.lastname
	end
	
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:update]
  before_action :client_belongs_to_user?
  skip_before_action :client_belongs_to_user?, only: [:index, :new, :create]
  # after_action :show, :client_belongs_to_user?
  # GET /clients
  # GET /clients.json
  def index
    @clients = current_user.clients
    render json: @clients
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    if client_belongs_to_user?
      @client = set_client
      initialize_client_attributes # FIND METHOD IN application_controller
      session[:current_client_id] = @client.id
    else
      flash[:message] = "Client not found"
      redirect_to '/dashboard'
    end
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  def nutritionaldata
    @client = set_client
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)
      if @client.save
        render :js => "loadClient(" + @client.id.to_s + ")"
      else
        render :new
      end
  end

  def error(kind)
    @client = Client.find(params[:id])
    respond_to do |format|
      if kind === 'same_as_last'
        format.js { render :js => "$('#modal-alert3').iziModal('setTitle', 'Identic to last');"}
      end
    end
  end

  def history
    @client = set_client
    @medical_records = @client.medical_records
    @fullassessments = @medical_records[:fullassessments]
    @progressnotes = @medical_records[:progressnotes]
    @labs = @medical_records[:labs]
    @monitoringnotes = @medical_records[:monitoringnotes]
    @nextevaluationnotes = @medical_records[:nextevaluationnotes]
    @goals = @medical_records[:goals]
    render :medical_history
  end

  def client_params1
      
  end
  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    @client = set_client
    @client.update(client_params)
    render json: @client
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { flash[:notice] = 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:id, :firstname, :lastname, :dob, :gender, :allergies, :user_id, :cdiet, :dx, :ht, :cbw, :date0, :thirtywt, :ninetywt, :oneeightywt, :date1, :date2, :date3, :intakefrom, :intaketo, :bmi, :ibw, :calreq, :proreq, :flreq, :fassess, :fpes, :pes0, :pes1, :pes2)
    end

    def client_belongs_to_user?
      if set_client.user_id != current_user.id
        @client = Client.new
        @client.errors.add(:user_id, "Client not found on your records")
        flash[:message] = {status: 'error', content: "Client not found on your records"}
        redirect_to root_path
      else true
      end
    end
end

app/views/clients/info.html.erb
<!-- START CLIENT INFO -->
<div id="clienloadleft" class="col-lg-3 box-holder">
  <div id="client-info-container" class="content-box profile-sidebar box-shadow boxed-info">
    <div class="profile-usertitle">

        <!-- CLIENT INFO SHOW -->
          <div class="profile-usertitle-name d-inline">
          <span id="client-firstname" style="font-size:28px;font-weight:150;float:left" class="client-attribute"><%= @client.firstname.capitalize %></span>
          <div style="float:left">&nbsp;</div>
          <span id="client-lastname" style="float:left;font-size:28px;font-weight:150;" class="client-attribute"><%= @client.lastname.capitalize %></span><br>
        </div>
          <div id="client-dob" class="profile-usertitle-job client-attribute">
            <%= @client.dob %>
          </div>
          <div id="client-gender" class="profile-usertitle-job client-attribute">
            <%= @client.gender %>
          </div>
      <div class="">
        <button id="client-edit-btn" type="button" class="btn waves waves-effect waves-float" data-fadeToggle="modal" data-target="#clienteditmodal" style="background: #374B89; color: #FFFFFF;">Edit</button>
      </div>
      <!-- END CLIENT INFO SHOW END -->


      <!-- START CLIENT NUTRITION PARAMS -->
      <div id="currentHealthParams" class="profile-usermenu" style="display: block">
        <ul class="nav">
          <div class="row">
            <li class="" style="display: inline-block; float: left" data-toggle="tooltip" data-placement="top" title="BMI">
              <span  id="bmispanin" class="green" style="font-size:30px"><%= @client.bmi %></span>
              <span class="emptygray" style="font-size:12px">kg/m2</span>
            </li>
            <li style="display: inline-block;float: right" data-toggle="tooltip" data-placement="top" title="Daily Caloric Requirement">
                <span id="calrequirement" class="black" style="font-size:30px;" ><%= @client.calreq %></span>
                <span class="emptygray" style="font-size:12px;">cal/day</span>
            </li>
          </div>
          <div class="row">
            <li class="" style="display: inline-block; float: left;margin-right: 20px" data-toggle="tooltip" data-placement="right" title="Ideal Body Weight">
                <span id="ibwspanin" class="black" style="font-size:30px"><%= @client.ibw %></span>
                <span class="emptygray" style="font-size:12px">lbs</span>
            </li>
            <li style="display: inline-block;float: right;margin-left: 20px" data-toggle="tooltip" data-placement="right" title="Daily Protein Requirement">
                <span  id="prorequirement" class="black" style="font-size:30px;"><%= @client.proreq %></span>
                <span class="emptygray" style="font-size:12px">g/day</span>
            </li>
          </div>
          <div class="row">
            <li class="" style="display: inline-block; float: left;margin-right: 30px" data-toggle="tooltip" data-placement="right" title="Percentage Ideal Body Weight">
              <span id="percentibw" class="yellow" style="font-size:30px">90</span>
              <span class="emptygray" style="font-size:12px">%ibw</span>
            </li>
            <li style="display: inline-block;float: right" data-toggle="tooltip" data-placement="bottom" title="Daily Fluid Requirement">
                <span id="flrequirement" class="black" style="font-size:30px;"><%= @client.flreq %></span>
                <span class="emptygray" style="font-size:12px">oz/day</span>
            </li>
          </div>
        </ul>
      </div>
      <!-- END CLIENT NUTRITION PARAMS END -->

  </div>

  <!-- CLIENT EDIT INFO FORM HIDDEN -->
  <div id="client-edit-form-container" class="content-box profile-sidebar box-shadow boxed-form away">
    <div class="profile-usertitle">
      <div class="form-group d-inline">
    <%= form_for @client, url: client_path, html: {class: "content-form", id: "client-edit-form"} do |f| %>
      <div class="field-container info">
        <%= f.text_field :firstname, class: "inin form-control material input-lg", id: "client-firstname-input", required: true %>
        <%= f.label :firstname, 'First Name', class: "inlabel" %>
      </div>
      <div class="field-container form-group info">
        <%= f.text_field :lastname, class: "inin form-control material input-lg", id: "client-lastname-input", required: true %>
        <%= f.label :lastname, 'Last Name', class: "inlabel" %>
      </div>
      <div class="field-container form-group info">
        <%= f.text_field :dob, class: "inin form-control material input-lg", id: "client-dob-input", required: true %>
        <%= f.label :dob, 'Date of Birth', class: "inlabel" %>
      </div>
      <div class="field-container form-group info">
        <%= f.text_field :gender, class: "inin form-control material input-lg", id: "client-gender-input", required: true %>
        <%= f.label :gender, 'Gender', class: "inlabel" %>
      </div>
      <%= f.submit 'Save', class: "actions btn waves waves-effect waves-float", style: "background: #5F9EA0; color: #FFFFFF;"%>
        <button id="client-cancel-edit-btn" type="button" class="btn waves waves-effect waves-float" data-fadeToggle="modal" data-target="#clienteditmodal" style="background: #374B89; color: #FFFFFF">Cancel</button>
    <% end %>
    <!-- CLIENT EDIT INFO FORM HIDDEN END -->
      </div>
    </div>
  </div>
</div>

  <!-- CLIENT GOALS -->
  <div class="content-box box-shadow big-box todo-list" style="position: absolute">
    <div class="sort-todo">
      <a class="active-todo">Active <span class="badge green-bg"></span></a>
      <a class="complete-todo">Completed <span class="badge yellow-bg"></span></a>
      <a class="archive-todo">Archived <span class="badge blue-bg"></span></a>
    </div>

      <%= form_for @goal, url: client_goals_path(@client), html: {id: "add-goal"} do |f| %>
        <div class="form-group add-todo">
          <div class="input-group">
            <label style="text-align: center">New Goal</label>
            <%= f.text_field :revision_date, id:"goal-revision-date", placeholder: "Revision Date", class: "form-control name-of-todo date", required: true%>
            <%= f.text_field :name, id:"goal-input", placeholder: "Goal", class: "form-control name-of-todo", required: true%>
            <%= f.submit 'Add Goal', class: 'btn text-uppercase', style:'background: #374B89;color: #FFFFFF;margin: 13px;float: right' %>
          </div>
        </div>
      <% end %>

      <div class="panel-body todo">
        <ul id="client-goals" class="list-group" style="margin: 0px">

          <%= render template: 'goals/show' %>

        </ul>
      </div>
  </div>
<!-- CLIENT GOAL END -->

</div>

app/views/clients/medical_history.html.erb
<div class="col-lg-9">
  <div class="tabbable tabs-with-bg">
    <ul class="nav nav-tabs nav-justified">
      <li class="active">
        <a href="#tab-1" data-toggle="tab">ADIME</a>
      </li>
      <li>
        <a href="#tab-2" data-toggle="tab">Progress Notes</a>
      </li>
      <li>
        <a href="#tab-3" data-toggle="tab">Monitoring Notes</a>
      </li>
    </ul>
    <div class="tab-content">

      <div class="tab-pane big-box  fade in active" id="tab-1">
        <ul class="cbp_tmtimeline" style=''>
          <% if !@fullassessments.any? %>
            <li style="width: 90%; height: 80px; background-color: #f1f4f5; color: black;text-align: center; margin-left: 55px">
              <div>
                <h3 style="position: absolute; top: 15%; left: 28%">Full Assessmentes will be displayed here.</h3>
              </div>
            </li>
          <% else %>
            <% @fullassessments.reverse.map do |fullassessment| %>
              <%= raw "<li><div class='cbp_tmlabel' style='margin-left: 0px;'><p style='font-size:18px;line-height:1.1'><h1>#{fullassessment.assessment_type} - #{fullassessment.created_at}</h1><h2>#{fullassessment.assessment}</h2> <h1>Diagnosis</h1><h2>#{fullassessment.diagnosis}</h2><h1>Intervention</h1><h2>#{fullassessment.intervention}</h2><h1>Monitoring/Evaluation - #{@client.nextevaluationnotes.last == nil ? "___Please include date on 'Next Evaluation Note'" : "Next due on #{@client.nextevaluationnotes.last.nnote_date}"}</h1><h2>#{fullassessment.monitoring_evaluation}</h2></p></div></li>" %>
            <% end %>
          <% end %>
        </ul>
      </div>

      <div class="tab-pane big-box  fade in" id="tab-2">
        <ul class="cbp_tmtimeline" style=''>
          <% if !@progressnotes.any? %>
            <li style="width: 90%; height: 80px; background-color: #f1f4f5; color: black;text-align: center; margin-left: 55px">
              <div>
                <h3 style="position: absolute; top: 15%; left: 28%">Progress notes saved on Assessments will be displayed here.</h3>
              </div>
            </li>
          <% else %>
            <% Progressnote.where(client_id: @client.id).all.reverse.map do |progressnote| %>
              <%= raw "<li><div class='cbp_tmlabel' style='margin-left: 0px;'><h2>#{progressnote.created_at.to_s.split(" ")[0]}</h2><p style='font-size:18px;line-height:1.1'>#{progressnote.pnote}</p></div></li>" %>
            <% end %>
          <% end %>
        </ul>
      </div>

      <div class="tab-pane big-box  fade in" id="tab-3">
        <ul class="cbp_tmtimeline" style=''>
          <% if !@monitoringnotes.any? %>
            <li style="width: 90%; height: 80px; background-color: #f1f4f5; color: black;text-align: center; margin-left: 55px">
              <div>
                <h3 style="position: absolute; top: 15%; left: 28%">Monitoring notes saved on Assessments be will displayed here.</h3>
              </div>
            </li>
          <% else %>
            <% @monitoringnotes.reverse.map do |monitoringnote| %>
              <%= raw "<li><div class='cbp_tmlabel' style='margin-left: 0px;'><h2>#{monitoringnote.created_at.to_s.split(" ")[0]}</h2><p style='font-size:18px;line-height:1.1'>#{monitoringnote.mnote}</p></div></li>" %>
            <% end %>
          <% end %>
        </ul>
      </div>

      <% if @labs.any? %>
      <!-- LABS FORM MODAL FOR LABS#EDIT-->
        <div id="labsform-2" class="iziModal" role="dialog">
          <div class="modal-dialog">
            <!-- Modal content-->
            <div class="content-box box-shadow big-box todo-list">
              <div style="">
                <div style="display: inline-block; widht: 100%"><h1 style="font-size: 3em" >Labs - </h1></div>
                <div style="display: inline-block">
                  <%= label_tag :date, "Date", style: "margin-bottom: 0px;left: 9px;position: relative;top: 3px;"  %>
                  <%= text_field_tag :date,value = @lab.date.strftime("%m/%d/%Y"), class: "summernote5", style: "border: 0; padding: 0 0 0 0.2em; font-size: 34px", readonly: 'readonly' %>
                  </div>
              </div>
                <div class="table-responsive">
                  <table id="datatable" class="table">
                    <thead>
                      <tr>
                        <th>Marker</th>
                        <th>Values</th>
                        <th>Ranges</th>
                      </tr>
                    </thead>
                    <tbody>
                    <% @labs.attributes.each_with_index do |lab, idx| %>
                      <% next if ["id", "client_id", "date", "created_at", "updated_at"].include?(lab[0]) %>
                      <tr class=<%= idx.odd? ? "active" : "" %>>
                        <th><%= lab[0].to_sym %></th>
                        <th>
                          <div class="form-group has-warning has-feedback">
                            <%= text_field_tag lab[0], value = @lab[lab[0]].to_s, readonly: 'readonly', class: "form-control no-margin-bottom" %>
                            <span class="glyphicon glyphicon-warning-sign form-control-feedback" aria-hidden="true"></span>
                          </div>
                        </th>  
                        <th style="font-size: 16px;"><%= Lab.ranges[lab[0].to_sym][:normal_adults][@client.gender.to_sym].join('').gsub("..", " - ") + " " + Lab.ranges[lab[0].to_sym][:metric]%></th>  
                      </tr>
                    <% end %>
                    </tbody>
                  </table>
                </div>
              <br><br>
            </div>
            
          </div>
        </div>
      <% end %> -->
      </div>
    </div>
  </div>

app/views/clients/show.html.erb
<!-- PAGE FOR CLIENT ID = <%= current_client %> -->

<!-- THIS HTML ELEMENT CONTAINS ALL CLIENT INFO -->
<div id="client" <%= @client.attributes.map { |attribute, value| "data-#{attribute}=#{value}" }.join(" ") %> style="display: none">
	
</div>


<!-- 
FULL PAGE DIVIDED INTO:
  1- SECTION 1 = Top Left Box (info) + Bottom Left Box (goals):
        CONTAINS CLIENT BASIC INFO (NAME, DOB, GENDER, AND NUTRITIONAL BASIC DATA)
  2- SECTION 2 = Top Right Box:
        DIV HOLDS PANEL WITH 'GATHER, ASSESS, COMPLY' TABS ALONG WITH WEIGHT HISTORY CHART AND INTAKE + FEEDING ASSISTANCE NEEDED -->

<!-- SECTION 1 ===> -->	<%= render template: 'clients/info' %>

<!-- SECTION 2 ===> --> <%= render template: 'clients/assessment_tool' %>