config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => {:sessions => "sessions"}

  devise_scope :user do 
    delete "/users/sign_out" => "devise/sessions#destroy" 
  end

  resources :users, only: [:show] do
    resources :clients, only: [:show, :new, :edit] do
    end
  end

  get '/clients/:id/history', to: 'clients#history' # custom route
  
  resources :clients, only: [:show, :index, :create, :update, :delete] do
      resources :history, :labs, :fullassessments, :progressnotes, :monitoringnotes, :nextevaluationnotes, :goals
  end
  
  root 'pages#home'

  get '#processingViewModal', to: 'pages#home' # hack in the meantime

  get '/dashboard', to: 'pages#dashboard'



 
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/_header.html.erb
fana<!-- HEADER STARTS -->
<ul id="gn-menu" class="gn-menu-main" style="z-index: 9999">
  <li class="gn-trigger">
    <a id="menu-toggle" class="menu-toggle gn-icon gn-icon-menu">
      <div class="hamburger">
        <span></span>
        <span></span>
        <span></span>
      </div>
      <div class="cross">
        <span></span>
        <span></span>
      </div>
    </a>
    <nav class="gn-menu-wrapper">
      <div class="gn-scroller">
  <% if current_user %>
        <ul class="gn-menu metismenu">
          <li>
            <a href="#" aria-expanded="false">
              <i class="fa fa-user"></i> Client<span class="fa arrow"></span></a>
            <ul class="gn-submenu collapse active" aria-expanded="false">
              <li>
                <a id="assessmentTool">Assessment Tool<span id="isClientLoaded" class="badge badge-danger" style="margin-left: 20px">Load Client</span></a>
              </li>
              <li id="historyFromMenu">
                <a type="button" aria-expanded="false">History</a>
              </li>
            </ul>
          </li>
<!--               <li>
                <a aria-expanded="false">
                  <i class="fa fa-cubes"></i>DNA
                  <span class="fa arrow"></span>
                </a>
                <ul class="gn-submenu collapse" aria-expanded="false">
                  <li><a>Connect new client</a></li>
                  <li><a>See connected clients</a></li>
                </ul>
              </li> -->

          <li>
            <a id="calendarFromMenu" aria-expanded="false"><i class="fa fa-television"></i>Dashboard<span class="fa arrow"></span></a>
          </li>
        </ul>
        </div>
        <div class="bottom-bnts">
          <a id="pinHeader" class="fix-nav" href="#"><i class="mdi mdi-pin"></i></a>
    <% else %>
    <% end %>
        </div>
        <!-- /gn-scroller -->
      </nav>
    </li>
    
    <li id="logoOnHeader" class="animated">
      <a class="logo-on-header">
        <!-- <%= image_tag 'Logo SOS.png', style: "position: absolute; display: block; height: 70px; top: -6px;left: 55px;"%> -->
      </a>
      <!-- <a class="logo">DIETITIAN.HELP<i class="fa fa-heartbeat"></i></a> -->
    </li>
    <% if current_user %>
      <li class="col-lg-3 row text-left">
        <div class="center-y-header">
          <span>logged in as:</span>
          <h3 class="d-inline"><%= link_to current_user.username, user_path(current_user), class: "name-on-header", style: "top: 11%;" %></h3>
        </div>
      </li>
    <% end %>
    <li class="row top-clock col-lg-2">
      <span class="current-time"></span>
    </li>
    <% if @current_client %>
      <li class="col-lg-3 row text-right">
        <div class="center-y-header">
          <span>On view:</span>
          <h3 id="displayClientOnHeader" class="d-inline client-on-header"><a href="#"class="name-on-header", style="top: 11%;" ></a></h3>
        </div>
      </li>
      <% end %>
    <li class="pull-right">
      <ul class="nav navbar-right right-menu">
        <div class="empty"></div>
        <% if !current_user %>
        <li>
          <a id="aboutFromNav">About</a>
        </li>
        <li>
          
        </li>
        <% else %>
        <li class="">
          <a id="searchHeaderIcon">
            <i class="fa fa-search-plus"></i>
          </a>
        </li>
        <li class="">
          <%= link_to destroy_user_session_path, :method => :delete, class: "logo" do %>
            <i class="fa fa-power-off"></i>
            <% end %>
          </a>
        </li>
        <% end %>
        
      </ul>
    </li>
  </ul>
  <!-- HEADER ENDS -->

<!-- JAVASCRIPT FROM HEADER BEGINS -->
<script>
// ONCLICK CALENDAR HEADER
$('#calendarFromMenu, #logoOnHeader').click(function() {
  top.$('#clientload').fadeOut()
  top.$('#clientload').attr('src', '/dashboard')
})

$('#searchHeaderIcon').click(function() {
  top.$('#searchAddModal').iziModal('open');
})

$('#pinHeader').click(function() {
  top.$('body').toggleClass('mini-nav')
  top.$('body').animate({
    marginLeft: top.$('body').hasClass('mini-nav') ? '60px' : '0'
  }, 300)
})

$('#accountFromMenu').click(function() {
  top.$('#clientload').fadeOut()
  <% if current_user %>
  top.$('#clientload').attr('src', '/users/' + <%= current_user ? current_user.id : "" %>)
  <% else %>
  <% end %>
})

</script>
<!-- JAVASCRIPT FROM HEADER ENDS-->

app/views/pages/dashboard.erb
  <div id="dashboard">
    <div class="content">
        <div class="col-lg-7">
          <div id="calendar" class="fc-calendar box-shadow"></div>
        </div>
      </div>
  
        <div class="col-lg-5">
        <div class="content-box big-box" style="margin: 0 10px 10px 10px">
        <h4 class="zero-m">Clients</h4>
        <div class="table-responsive">
          <table id="datatable" class="table">
            <caption>Use search box to find clients.</caption>
            <thead>
              <tr>
                <th>ID</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Next Assessment Date</th>
              </tr>
            </thead>
            <tbody>
              <% @clients.each_with_index do |client, idx| %>
              <% if client.id != nil%>
              <!-- CREATES CLIENT TABLE IN DB // GRAY AND WHITE TABLES -->
              <tr id=<%="#{client.id}"%> class=<%= idx.odd? ? "active clientsOnTable" : "clientsOnTable" %> onclick="top.loadClient(<%=client.id%>)" style="cursor: pointer">
                <th scope="row"><%=client.id%></th>
                <td><%=client.firstname%></td>
                <td><%=client.lastname%></td>
                <% if client.nextevaluationnotes.last != nil %> 
                  <td><%=client.nextevaluationnotes.last.nnote_date%></td>
                <% else %>
                  <td>- -</td>
                <%end %>
              </tr>
              <% else %>
              <% end %>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
      </div>
</div>

      <!-- INITIALIZE CALENDAR () -->
<script>
top.$currentClient = 0
  // DOCUMENT READY
$(document).ready(function() {


  <% to_do_today = {} %>
  $(function() {
    $(".event-tag span").click(function() {
      $(".event-tag span").removeClass("selected");
      $(this).addClass("selected");
    });
    $(document).on('click', '.remove-event', function(e) {
      $(this).parent().remove();
    });
    /* initialize the calendar */
    var date = new Date();
    var d = date.getDate();
    var m = date.getMonth();
    var y = date.getFullYear();
    $('#calendar').fullCalendar({
      header: {
        left: 'prev, next',
        center: 'title',
        right: 'today, month,agendaWeek,agendaDay'
      },
      //Add Events
      // FETCHING FROM ALL USER'S CLIENTS --- ATOMATICALLY ADDS 5 DAYS TO NEXTEVALUATIONNOTE_DATE TO = ENDDATE IN CALENDAR
      // MONTHS FROM CALENDAR PLUGIN ARE AHEAD BY 1 WILL DO -1 ON ALL MONTHS TO MATCH CALENDAR OUTPUT -- SEE start_date[1]
      events: [<% if @nextevaluationnotes.present? %>
        <% @nextevaluationnotes.map do |nextevaluationnote| %>
        // start_date = original next evaluation date - 1 month
        <% start_date = nextevaluationnote.nnote_date.to_s.split("-").map(&:to_i) %>
        <% start_date[1] = start_date[1] - 1 %>
        // end_date = original next evaluation date = - 1 month and + 5 days
        <% end_date = nextevaluationnote.nnote_date.to_s.split("-").map(&:to_i)%>
        <% end_date[2], end_date[1] = (end_date[2] + 5), (end_date[1] - 1) %>
        // start_date_range = original next evaluation date (no modification, used to push to due_today)
        <% start_date_range = nextevaluationnote.nnote_date.to_s.split("-") %>
        <%= raw "{" %>
        <%= raw "title: '#{Client.find(nextevaluationnote.client_id).firstname.to_s} #{Client.find(nextevaluationnote.client_id).lastname.to_s}'," %>
        <%= raw "start:" + ' new Date(' + start_date.join(", ") + ")," %>
        <%= raw "end:" + ' new Date(' + end_date.join(", ") + ")," %>
        <%= raw "time:" + "'4pm'," %>
        <%= raw "className:" + "''},"%>
        // compares if today's date is between nnote_date -- nnote_date + 5 and pushes to to_do_today as hash
        // ASSESSMENT DATE RANGE
        <% Date.parse(Time.now.to_s).between?(Date.parse(start_date_range.join("-").to_s), Date.parse(start_date_range.join("-").to_s) +5) ? to_do_today["#{Client.where(id: nextevaluationnote.client_id).first.id}"] = nextevaluationnote.nnote_date.to_s : "" %>
        <% end %>
        <% end %>
      ],
      editable: false,
      eventLimit: false,
      droppable: false, // this allows things to be dropped onto the calendar
      drop: function(date, allDay) { // this function is called when something is dropped
        // retrieve the dropped element's stored Event Object
        var originalEventObject = $(this).data('eventObject');
        // we need to copy it, so that multiple events don't have a reference to the same object
        var copiedEventObject = $.extend({}, originalEventObject);
        // assign it the date that was reported
        copiedEventObject.start = date;
        copiedEventObject.allDay = allDay;
        // render the event on the calendar
        // the last `true` argument determines if the event "sticks" (http://arshaw.com/fullcalendar/docs/event_rendering/renderEvent/)
        $('#calendar').fullCalendar('renderEvent', copiedEventObject, true);
        // is the "remove after drop" checkbox checked?
        if ($('#drop-remove').is(':checked')) {
          // if so, remove the element from the "Draggable Events" list
          $(this).remove();
        }
      }
    });
  });

});
//UltraWidget
function widgetUsed(id, number, string) {
  $("#" + id).prop('Counter', 0).animate({
    Counter: number
  }, {
    duration: 800,
    easing: 'swing',
    step: function(now) {
      $("#" + id).text(now.toFixed(0));
    }
  });
};
// HASH CONTAINING CLIENT ID AND NEXT EVALUATION DATE DUE TODAY
var dueToday = {
    <% to_do_today.map do |key, val| %>
    <%= raw key + ":" + "'" + val.to_s + "'," %>
    <% end -%>
  }
  // CHANGES COLOR OF CLIENTS ON TABLE THAT ARE DUE TODAY BY COMPARING WITH CLIENTS IN dueToday
$.makeArray($('.clientsOnTable')).forEach(function callback(currentValue, index, array) {
  if (dueToday[currentValue.id]) {
    document.getElementById(currentValue.id.toString()).className = "danger";
  }
});
widgetUsed("dueTodayCnt", <%=to_do_today.count %>);
// FOR CLIENTS DATATABLE TO WORK
$(function() {
  //Data Tables
  $('#datatable').DataTable({
    displayLength: 10,
    dom: 'T<"clear">lfrtip',
    tableTools: {
      "sSwfPath": "datatables/copy_csv_xls_pdf.swf",
      "aButtons": []
    },
    responsive: true
  });
});
toDoToday = <%= raw  to_do_today.to_a.flatten %>;


window.onload = function() {
  top.$('#clientload').show()
  top.$('#historyFromMenu').remove();

}
</script>

app/views/pages/home.html.erb
  <!-- PRELOADER/SLOGAN HIDDEN-->
    <div id="preloader" class="preloader table-wrapper" style="background: white;">
      <div class="table-row">
        <div id="contente" class="contente" style="display: none">
          <div id='visiblee' class="preloader-animate">
            <p>
            </p>
            <ul id="preloader-list" style="">
              <li >_Gather.</li>
              <li >_Assess.</li>
              <li>_Comply.</li>
              <li>_Done.</li>
            </ul>
          </div>
        </div>
      </div>
    </div>


    <!-- BEGIN SEARCH/ADD MODAL HIDDEN-->
    <div id="searchAddModal" class="" style="display: none">
      <div style="visibility:visible;z-index:900;position: fixed; display: inline-block;top: 25%;left: 30%;height:auto;width:500px" class="table-wrapper">
        <div class="bgblur">
          <div class="table-cell text-center">
            <div class="landingfront pagenotfound">
              <div class="content-box box-shadow">
                <div class="top">
                  <h1 class="" style="margin:0.67em 0 -0.3em;">Search/Add</h1>
                  <a class="fa-stack fa-2x icon-back">
                    <i class="fa fa-circle fa-stack-2x blue"></i>
                    <i class="fa fa-long-arrow-left fa-stack-1x fa-inverse"></i>
                  </a>
                </div>
                <form class="big-box">
                  <a class="fa-stack fa-2x icon-home" style="top:52%;z-index:1500" type="submit" name="commit" value="Create Client" data-disable-with="Create Client">
                    <i class="fa fa-circle fa-stack-2x yellow"></i>
                    <i id="landsearchicon" class="fa fa-search fa-stack-1x fa-inverse"></i>
                  </a>
                  <div class="form-group">
                    <input id="select-beast-landsearch" type="search" class="gn-search form-control material" placeholder="" autofocus>
                  </div>
                  <label for="select-beast-landsearch">Name</label>
                </form>
                <div id="new-client-form-container" class="hidden-form" style="display: none; margin-top: -30px">
                  <%= form_for @client, url: clients_path, html: {id: "new-client-form", class: "content-form form-inline", remote: true} do |f| %>
                  <div  class="field-container form-group" style="dispaly: none;" >
                    <%= f.text_field :firstname, id: "new-firstname-input", type: "string", class: "inin form-control material input-lg", style: "height: 33px;padding: 0px;margin: 0px;", required: true%>
                    <%= f.label :firstName, "First Name", style: "margin: 0px;", class: "" %>
                  </div>
                  <div  class="field-container form-group" >
                    <%= f.text_field :lastname, id: "new-lastname-input", type: "string", class: "inin form-control material input-lg", style: "height: 33px;padding: 0px;margin: 0px;", required: true %>
                    <%= f.label :lastname, "Last Name", style: "margin: 0px;", class: "" %>
                  </div>
                  <div  class="field-container form-group hidden" >
                    <%= f.text_field :user_id, type: "integer", value: current_user.id, readonly: 'readonly', id: "provider-input", class: "inin form-control material input-lg", style: "height: 33px;padding: 0px;margin: 0px;", required: true %>
                    <%= f.label :provider, "Provider ID", style: "margin: 0px;", class: "" %>
                  </div>
                  <div  class="field-container form-group" >
                    <%= f.text_field :dob, id: "hiddendob", type: "text", class: "inin form-control material input-lg", style: "height: 33px;padding: 0px;margin: 0px;",required: true %>
                    <%= f.label :dob, "Date of Birth", style: "margin: 0px;", class: "" %>
                  </div>
                  <div  class="field-container form-group" >
                    <%= f.text_field :gender, id: "hiddengender", placeholder: "'Male', 'Female'",type: "string", class: "inin form-control material input-lg", style: "height: 33px;padding: 0px;margin: 0px;", required: true %>
                    <%= f.label :gender, "Gender", style: "margin: 0px;", class: "" %>
                  </div>
                  <div  class="field-container form-group" >
                    <%= f.text_field :cbw, id: "hiddencbw", type: "string", class: "inin form-control material input-lg", style: "height: 33px;padding: 0px;margin: 0px;", placeholder: "lbs",required: true %>
                    <%= f.label :cbw, "CBW", style: "margin: 0px;", class: "" %>
                  </div>
                  <div  class="field-container form-group" >
                    <%= f.text_field :ht, id: "hiddenht", type: "string", class: "inin form-control material input-lg", style: "height: 33px;padding: 0px;margin: 0px;", placeholder: "inches", required: true %>
                    <%= f.label :ht, "Height", style: "margin: 0px;", class: "" %>
                  </div>
                  <div  id="hiddensubmit">
                    <%= f.submit "Create Client", class: "btn btn-lg" %>
                  </div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- HEADER -->
    <div><%= render partial: 'pages/header' %></div>
      <!-- IFRAME WHERE ALL ACTIONS TAKE PLACE  -->
      <div style="height: 100%">
      <iframe name="clientload" aria-hidden="true" id="clientload" src="/dashboard" frameborder="0" height="900px" width="100%" scrolling="no" ></iframe>
    </div>
  <script>
    var progressBar    = top.NProgress

    var $currentUser    = <%= current_user.id %>
    var $currentClient = undefined // assigned on clientLoad (home-ux.js)
    var clientsJSON    = $.getJSON('/clients', data => JSON.stringify(data))

    progressBar.start()

    <% if flash[:message].present? %>
    toast('<%= raw flash[:message]["content"] %>', '#ab3737', '<%= raw flash[:message]["status"] %>')
    <% end %>
  </script>
</html>