config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => {:sessions => "sessions"}

  devise_scope :user do 
    delete "/users/sign_out" => "devise/sessions#destroy" 
  end

  resources :users, only: [:show] do
    resources :clients, only: [:show, :new, :edit] do
    end
  end

  get '/clients/:id/history', to: 'clients#history' # custom route
  
  resources :clients, only: [:show, :index, :create, :update, :delete] do
      resources :history, :labs, :fullassessments, :progressnotes, :monitoringnotes, :nextevaluationnotes, :goals
  end
  
  root 'pages#home'

  get '#processingViewModal', to: 'pages#home' # hack in the meantime

  get '/dashboard', to: 'pages#dashboard'



 
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :client

  # before_update :update do |x|
  # 	@status_before = Goal.where(id: x.id).first.status
  # 	@status_after = x.status
  # 	if @status_before == 'active' && @status_after == 'archive'
  		
  # 	end

  # end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :set_goal, only: [:show, :edit, :update, :destroy]
  skip_before_action :client_loaded_same_as_params?, only: [:show, :index]

  # GET /goals
  # GET /goals.json
  def index
    @goals = Goal.where(client_id: $current_client.id)
  end

  # GET /goals/1
  # GET /goals/1.json
  def show
    @goal = Goal.find(params[:id])
  end

  # GET /goals/new
  def new
    @goal = Goal.new
  end

  # GET /goals/1/edit
  def edit
    @goal = set_goal
  end

  # POST /goals
  # POST /goals.json
  def create
    @goal = Goal.new(goal_params)
    @goal.client_id = params[:client_id]
    @goal.status = 'active'

      if @goal.save
        flash[:message] = "Goal saved"
        render json: @goal.to_json
      else
      end
  end

  # PATCH/PUT /goals/1
  # PATCH/PUT /goals/1.json
  def update
      if @goal.update(goal_params)
        flash[:message] = "Goal saved"
        render json: @goal.to_json
      else
        render json: @goal.to_json
      end
  end

  # DELETE /goals/1
  # DELETE /goals/1.json
  def destroy
    if @goal.destroy
      flash[:message] = "Goal saved"
      render json: @goal.to_json
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_goal
      @goal = Goal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def goal_params
      params.require(:goal).permit(:client_id, :name, :revision_date, :status)
    end
end

app/views/goals/show.html.erb
<!-- CONDITION STYLES GOALS BASED ON STATUS -ACTIVE-COMPLETE-ARCHIVED -->

<% if @client.goals != nil %>
  <% @client.goals.each do |goal| %>
    <% status = goal.status %>
      
    <% if status == 'active' %>
      <li id="item-<%= goal.id%>" class="list-group-item  list-info list-item" data-toggle="tooltip" data-placement="top" title="<%= goal.revision_date%>">

        <div class="checkbox" onclick="updateGoal('<%= client_goal_path(@client, goal) %>', <%=goal.id%>, 'complete')">
          <input type="checkbox" id="<%= goal.id%>" >
          <label for="<%= goal.id%>"><%= goal.name%></label>
        </div>

        <div class="pull-right action-btns">
          <a class="archive" onclick="updateGoal('<%= client_goal_path(@client, goal) %>', <%=goal.id%>, 'archived')">
            <span class="fa fa-archive fa-inverse" style="cursor: pointer"></span>
          </a>

          <a class="delete-btn">
            <span class="fa fa-close fa-inverse delete-btn" style="cursor: pointer"></span>
          </a>
        </div>
      </li>

    <% elsif status == 'complete' %>
      <li id="item-<%= goal.id%>" class="list-group-item  list-info ui-sortable-handle checked-todo" data-toggle="tooltip" data-placement="top" title="<%= goal.revision_date%>">

        <div class="checkbox" onclick="updateGoal('<%= client_goal_path(@client, goal) %>', <%=goal.id%>, 'active')">
          <input type="checkbox" id="<%= goal.id%>" checked=true>
          <label for="<%= goal.id%>"><%= goal.name%></label>
        </div>

        <div class="pull-right action-btns">
          <a class="activate" onclick="updateGoal('<%= client_goal_path(@client, goal)  %>', <%=goal.id%>, 'active')">
            <span class="fa fa-check fa-inverse" style="cursor: pointer"></span>
          </a>

          <a class="delete-btn">
            <span class="fa fa-close fa-inverse delete-btn" style="cursor: pointer"></span>
          </a>
        </div>
      </li>

    <% elsif status == 'archived' %>
      <li id="item-<%= goal.id%>" class="list-group-item list-info archive-item" data-toggle="tooltip" data-placement="top" title="" data-original-title="<%= goal.revision_date%>" style="display: block;">
        <div class="checkbox" onclick="updateGoal('<%= client_goal_path(@client, goal) %>', <%=goal.id%>, 'complete')">
          <input type="checkbox" id="<%= goal.id%>">
          <label for="<%= goal.id%>"><%= goal.name%></label>
        </div>

        <div class="pull-right action-btns">
          <a class="e" onclick="updateGoal('<%= client_goal_path(@client, goal)  %>', <%= goal.id%>, 'active')">
            <span class="fa fa-check fa-inverse" style="cursor: pointer"></span>
          </a>

          <a class="delete-btn">
            <span class="fa fa-close fa-inverse delete-btn" style="cursor: pointer"></span>
          </a>
        </div>
      </li>


    <% end %>
  <%end %>
<% end %>